from __future__ import annotations

from . import providers
from .bundle import (
    bundle_manifest,
    inspect_bundle,
    md_cell,
    render_brief,
    write_bundle_outputs,
)
from .cli import build_parser, main, parse_providers, run_search
from .models import (
    BUNDLE_FILES,
    BUNDLE_FORMAT_VERSION,
    CONCEPT_PHRASES,
    DEFAULT_PROVIDERS,
    DEFAULT_WORKERS,
    PROFILE_EXPANSIONS,
    REQUIRED_BUNDLE_FILES,
    QueryRecord,
    SourceRecord,
    append_jsonl,
    now_iso,
    parse_year,
    slug,
    stable_id,
    write_json,
)
from .net import fetch_json, fetch_text, post_json
from .providers import (
    PROVIDER_EXCEPTIONS,
    PROVIDER_NEXT_ALLOWED_AT,
    PROVIDER_RATE_LIMIT_SECONDS,
    PROVIDER_RATE_LOCK,
    SEARCHERS,
    parse_pubmed_articles,
    provider_error,
    provider_search,
    provider_task,
    run_provider_queries,
    search_arxiv,
    search_openalex,
    search_pubmed,
    search_semantic_scholar,
    search_tavily,
    uninvert_abstract,
    wait_for_provider_rate_limit,
    xml_text,
)
from .ranking import (
    dedupe_sources,
    evidence_rows,
    focus_ranked_sources,
    score_sources,
    search_phrases,
    source_matches,
    source_url,
)
from .queries import (
    allosteric_switch_queries,
    biomol_expansions_for,
    make_queries,
    unique_query_records,
)

# Backward-compatible module handles used by tests and downstream monkeypatching.
os = providers.os
time = providers.time

__all__ = [
    "BUNDLE_FILES",
    "BUNDLE_FORMAT_VERSION",
    "CONCEPT_PHRASES",
    "DEFAULT_PROVIDERS",
    "DEFAULT_WORKERS",
    "PROFILE_EXPANSIONS",
    "PROVIDER_EXCEPTIONS",
    "PROVIDER_NEXT_ALLOWED_AT",
    "PROVIDER_RATE_LIMIT_SECONDS",
    "PROVIDER_RATE_LOCK",
    "QueryRecord",
    "REQUIRED_BUNDLE_FILES",
    "SEARCHERS",
    "SourceRecord",
    "allosteric_switch_queries",
    "append_jsonl",
    "biomol_expansions_for",
    "build_parser",
    "bundle_manifest",
    "dedupe_sources",
    "evidence_rows",
    "fetch_json",
    "fetch_text",
    "focus_ranked_sources",
    "inspect_bundle",
    "main",
    "make_queries",
    "md_cell",
    "now_iso",
    "os",
    "parse_providers",
    "parse_pubmed_articles",
    "parse_year",
    "post_json",
    "provider_error",
    "provider_search",
    "provider_task",
    "providers",
    "render_brief",
    "run_provider_queries",
    "run_search",
    "score_sources",
    "search_arxiv",
    "search_openalex",
    "search_phrases",
    "search_pubmed",
    "search_semantic_scholar",
    "search_tavily",
    "slug",
    "source_matches",
    "source_url",
    "stable_id",
    "time",
    "uninvert_abstract",
    "unique_query_records",
    "wait_for_provider_rate_limit",
    "write_bundle_outputs",
    "write_json",
    "xml_text",
]
